version: '3.4'
#TODO: how to upload outlook_mail schema to zookeeper?
#TODO: automate mapping/schema creation
#TODO: IMPORTANT!!! UPLOAD OUTLOOK_MAIL CONFIG TO ZOOKEEPER. WHO IS RESPONSIBLE?
#TODO: eliminate duplication of configuration
#TODO: esure proper start-up ordering (Elasticsearch must run before logstash)
#TODO: check fault tolerance & restartability
#TODO: mount config directories!!!
#TODO: how to join different networks? (between real PCs)
services:
#ELASTICSEARCH CLUSTER
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: zubtsov-es1
    env_file: ./elasticsearch-env/src/main/resources/elastic_common.env
    environment:
      - node.name=first-node
      - network.host=elasticsearch1
      - discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      mailuploadernet:
        ipv4_address: 192.168.1.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: zubtsov-es2
    env_file: ./elasticsearch-env/src/main/resources/elastic_common.env
    environment:
      - node.name=second-node
      - network.host=elasticsearch2
      - discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      mailuploadernet:
        ipv4_address: 192.168.1.1
    ulimits:
      memlock:
        soft: -1
        hard: -1

#SOLR CLUSTER
  solr1:
    image: solr:7.2.1
    container_name: zubtsov-solr1
    environment:
      - ZK_HOST=zoo1,zoo2
    ports:
     - 8983:8983
    volumes:
      - solrdata1:/opt/solr/server/solr/mycores #TODO: how to locate/reside all cores in this folder?
    networks:
      mailuploadernet:
        ipv4_address: 192.168.2.0
  solr2:
      image: solr:7.2.1
      container_name: zubtsov-solr2
      environment:
        - ZK_HOST=zoo1,zoo2
      ports:
       - 8984:8983
      volumes:
        - solrdata2:/opt/solr/server/solr/mycores #TODO: how to locate/reside all cores in this folder?
      networks:
        mailuploadernet:
          ipv4_address: 192.168.2.1

#ZOOKEEPER TODO: how to bind to normal ip address (not 0.0.0.0)?
  zoo1:
    image: zookeeper
    container_name: zubtsov-zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    volumes:
      - zoo1data:/data
      - zoo1datalog:/datalog
    networks:
          mailuploadernet:
            ipv4_address: 192.168.3.0
  zoo2:
    image: zookeeper
    container_name: zubtsov-zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    volumes:
      - zoo2data:/data
      - zoo2datalog:/datalog
    networks:
          mailuploadernet:
            ipv4_address: 192.168.3.1

#LOGSTASH TODO: move to IMAP
  logstash:
    image: logstash-zubtsov:latest
    container_name: zubtsov-logstash
    environment:
      - LOG_LEVEL=info
    ports:
      - 9600:9600
    networks:
      mailuploadernet:
        ipv4_address: 192.168.4.0
    volumes:
      - logstashdata:/usr/share/logstash/data

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  solrdata1:
    driver: local
  solrdata2:
    driver: local
  zoo1data:
    driver: local
  zoo1datalog:
    driver: local
  zoo2data:
    driver: local
  zoo2datalog:
    driver: local
  logstashdata:
    driver: local

networks:
  mailuploadernet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16