version: '3.4'
#TODO: eliminate duplication of configuration
services:
  elasticsearch:
    image: elasticsearch-zubtsov:latest
    container_name: zubtsov-es1
    environment:
      - cluster.name=zubtsov-es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: elasticsearch-zubtsov:latest
    container_name: zubtsov-es2
    environment:
      - cluster.name=zubtsov-es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  logstash:
      image: logstash-zubtsov:latest
      container_name: zubtsov-logstash
      ports:
        - 9600:9600
      networks:
        - esnet
      #TODO: add persistent volume for sincedb files
  solr:
    image: solr-zubtsov
    container_name: zubtsov-solr
    ports:
     - 8983:8983
    volumes:
      - solrdata:/opt/solr/server/solr/mycores
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  solrdata:
    driver: local

networks:
  esnet: